[package]
name = "logicraft"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
peg = "0.8.4"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.19"
